### ISSUE TITLE
Error occurs after updating to next@9.1.3

### ISSUE THREAD

**Issue by jim-king-2000** [zeit/next.js#9362]
# Bug report

## Describe the bug
Updating to next@9.1.3, the error message is :
"Uncaught (in promise) TypeError: isomorphic_unfetch__WEBPACK_IMPORTED_MODULE_0__ is not a function"

## To Reproduce

No reproduce yet.

## Expected behavior

It works on next@9.1.2.

## Screenshots

<img width="537" alt="Untitled" src="https://user-images.githubusercontent.com/7019050/68538222-cfded680-03ab-11ea-95f8-b07679e521b7.png">

## System information

- OS: [e.g. macOS, Windows] win10
- Browser (if applies) [e.g. chrome, safari] chrome@latest
- Version of Next.js: [e.g. 6.0.2] 12.13.0 & 13.1.0

## Additional context

I'll try to make a reproduce and keep posted.

**Comment by Timer** [comment]
Please provide a reproduction!

How are you importing `isomorphic-unfetch`? Can you show some details on how you're using it?

**Comment by Timer** [comment]
cc @janicklas-ralph

**Comment by jim-king-2000** [comment]
I import 'isomorphic-unfetch' for sure. Because it works on next@9.1.2.

**Comment by jim-king-2000** [comment]
The reproduction is not so easy. I have to extract the relevant code from a large project. But I'm still investigating which part of code is relevant.

**Comment by jim-king-2000** [comment]
The usage of `isomorphic-unfetch` is like the following. The root project 'bus' calls the module 'bus-store' and then calls another module 'bus-sdk'. The function "TSDBClient.getLastPosition" is in 'bus-sdk'. But the `isomorphic-unfetch` is installed in 'bus' project.

**Comment by Timer** [comment]
Which of these two options are you using?

```js
// Option 1
import fetch from 'isomorphic-unfetch'

// Option 2
const fetch = require('isomorphic-unfetch')
```

**Comment by Timer** [comment]
I've added a test for Option 2 here:
https://github.com/zeit/next.js/pull/9363

It seems to be failing, so I'm guessing this is the problem.

**Comment by jim-king-2000** [comment]
> Which of these two options are you using?
> 
> ```js
> // Option 1
> import fetch from 'isomorphic-unfetch'
> 
> // Option 2
> const fetch = require('isomorphic-unfetch')
> ```

Option 1, of course.

**Comment by jim-king-2000** [comment]
I still can't make a reproduction. However, I'm so glad that the suspect is arrested so quickly.

**Comment by jim-king-2000** [comment]
I make a reproduction successfully.

```javascript
// project root, index.js
import React, { Component } from 'react'
import getStar from 'react-module'

class Page extends Component {
  async componentDidMount() {
    const res = await getStar()
    console.log(await res.json())
  }

  render() {
    return <div>abc</div>
  }
}

export default Page
```

```javascript
// project root, package.json
"dependencies": {
    "isomorphic-unfetch": "^3.0.0",
    "next": "^9.1.3",
    "next-transpile-modules": "^2.3.1",
    "react": "^16.11.0",
    "react-module": "git+https://github.com/jim-king-2000/react-module.git"
  }
```

```javascript
// project 'react-module'
import fetch from 'isomorphic-unfetch'

export default function getStar() {
  return fetch('https://api.github.com/repos/zeit/next.js');
}
```

We have to call the function exported from the 3rd-module in browser(client-side rendering). It works if we use "getInitialProps". It also works if we call fetch directly in the root project.

**Comment by Timer** [comment]
Can you please upgrade to `next@9.1.4-canary.2` and see if it works for you?

**Comment by jim-king-2000** [comment]
Sure. I'll do it immediately.

**Comment by jim-king-2000** [comment]
It works. The fix is effective.

**Comment by Timer** [comment]
Excellent, thanks for testing so fast! You can remain on that version until we release the next stable.

**Comment by jim-king-2000** [comment]
Sure. And thank you for fixing it within such a short time.

**Comment by bbigras** [comment]
I don't seem able to use the [`delete win.fetch` trick with cypress](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/stubbing-spying__window-fetch#deleting-fetch) anymore.

I get:

```
cypress_runner.js:177710 Uncaught TypeError: Cannot read property 'bind' of undefined

This error originated from your application code, not from Cypress.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the 'uncaught:exception' event.

https://on.cypress.io/uncaught-exception-from-application
    at Object../node_modules/next/dist/build/polyfills/fetch/index.js (http://localhost:3000/_next/static/runtime/main.js?ts=1574289812052:4662:40)
    at __webpack_require__ (http://localhost:3000/_next/static/runtime/webpack.js?ts=1574289812052:793:31)
    at fn (http://localhost:3000/_next/static/runtime/webpack.js?ts=1574289812052:151:20)
    at Object../node_modules/next/dist/client/dev/event-source-polyfill.js (http://localhost:3000/_next/static/runtime/main.js?ts=1574289812052:5481:39)
    at __webpack_require__ (http://localhost:3000/_next/static/runtime/webpack.js?ts=1574289812052:793:31)
    at fn (http://localhost:3000/_next/static/runtime/webpack.js?ts=1574289812052:151:20)
    at Object.<anonymous> (http://localhost:3000/_next/static/runtime/main.js?ts=1574289812052:7562:51)
    at Object../node_modules/next/dist/client/next-dev.js (http://localhost:3000/_next/static/runtime/main.js?ts=1574289812052:7642:30)
    at __webpack_require__ (http://localhost:3000/_next/static/runtime/webpack.js?ts=1574289812052:793:31)
    at checkDeferredModules (http://localhost:3000/_next/static/runtime/webpack.js?ts=1574289812052:46:23)
From previous event:
    at run (http://localhost:3000/__cypress/runner/cypress_runner.js:100171:15)
    at Object.cy.(anonymous function) [as visit] (http://localhost:3000/__cypress/runner/cypress_runner.js:100537:11)
    at Context.runnable.fn (http://localhost:3000/__cypress/runner/cypress_runner.js:100724:20)
    at callFn (http://localhost:3000/__cypress/runner/cypress_runner.js:30931:21)
    at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:3000/__cypress/runner/cypress_runner.js:30924:7)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:103593:28
From previous event:
    at Object.onRunnableRun (http://localhost:3000/__cypress/runner/cypress_runner.js:103582:17)
    at $Cypress.action (http://localhost:3000/__cypress/runner/cypress_runner.js:97300:30)
    at Test.Runnable.run (http://localhost:3000/__cypress/runner/cypress_runner.js:102519:20)
    at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (http://localhost:3000/__cypress/runner/cypress_runner.js:31398:10)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:31504:12
    at next (http://localhost:3000/__cypress/runner/cypress_runner.js:31318:14)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:31328:7
    at next (http://localhost:3000/__cypress/runner/cypress_runner.js:31260:14)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:31296:5
    at timeslice (http://localhost:3000/__cypress/runner/cypress_runner.js:26364:27)
logError @ cypress_runner.js:177710
(anonymous) @ cypress_runner.js:177383
emit @ cypress_runner.js:141352
(anonymous) @ cypress_runner.js:121660
emit @ cypress_runner.js:141352
emit @ cypress_runner.js:121692
_onErrorClick @ cypress_runner.js:120577
(anonymous) @ cypress_runner.js:121811
executeAction @ cypress_runner.js:161008
res @ cypress_runner.js:160999
ca @ cypress_runner.js:169014
ja @ cypress_runner.js:169015
ka @ cypress_runner.js:169015
wa @ cypress_runner.js:169017
Aa @ cypress_runner.js:169018
ya @ cypress_runner.js:169018
Da @ cypress_runner.js:169021
Ad @ cypress_runner.js:169084
Gi @ cypress_runner.js:169250
Kb @ cypress_runner.js:169039
Dd @ cypress_runner.js:169086
(anonymous) @ cypress_runner.js:169251
./node_modules/react-dom/node_modules/scheduler/cjs/scheduler.production.min.js.exports.unstable_runWithPriority @ cypress_runner.js:169330
Ii @ cypress_runner.js:169251
Cd @ cypress_runner.js:169085
```

**Comment by jim-king-2000** [comment]
Tyr `next@9.1.4`?

**Comment by bbigras** [comment]
I have the problem with 9.1.4. I didn't have it with 9.1.2. I thought it could be related to this issue's fix.

**Comment by jim-king-2000** [comment]
You can raise a new bug.

**Comment by bbigras** [comment]
Someone else did https://github.com/zeit/next.js/issues/9483

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
