### ISSUE TITLE
Error: Cannot find module 'postcss-flexbugs-fixes' after upgrading to 9.3.4

### ISSUE THREAD

**Issue by pjaws** [zeit/next.js#11783]
# Bug report

## Describe the bug

`next build` fails with the error in the title after updating to 9.3.4 with a custom PostCSS config following the current documentation

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a `postcss.config.js` with the contents specified [here](https://nextjs.org/docs/advanced-features/customizing-postcss-config)
2. Update to 9.3.4
3. No more builds!

## Expected behavior

Documentation needs to be updated with the correct "base" PostCSS config for 9.3.4. I know you apparently removed `postcss-flexbugs-fixes`, but I have no idea what else might have changed.

**Comment by Timer** [comment]
You need to install these dependencies yourself, otherwise you're relying on an implicit dependency from Next.js. We might need to update the docs to make this more clear.

**Comment by pjaws** [comment]
No, this is a problem with documentation not being correctly updated when a change was made. Your documentation says "This is the default configuration used by Next.js:". If that's not true anymore after an update, then it needs to be changed.

These aren't MY dependencies, they're yours. I wouldn't have them in this file if you didn't tell me to.

Another option for things like this would be to expose a way of importing the default config. I think that would probably be the best option for both you and the users.

**Comment by timneutkens** [comment]
> These aren't MY dependencies, they're yours. I wouldn't have them in this file if you didn't tell me to.

The moment you reference a dependency in your application configuration like postcss.config.js it's a dependency of your project.

Definitely can be mentioned in the docs that you have to install it, but you can't reference internal npm dependencies of other dependencies (like next.js) in a safe way as dependencies can change at any time.

An example would be (generic node.js example), you add `fs-extra` to your project and then import `rimraf` without adding it to your dependencies.

If you want to rely on Next.js configuring postcss you don't add postcss.config.js, otherwise it's up to you as a user to configure it and add the correct dependencies.

**Comment by pjaws** [comment]
That's fair, but the documentation should also be updated when you change something like this. If a user right now goes and follows the advice in your docs, their application will break!

Again, the ideal solution would be to offer a way of extending or importing your base config.

**Comment by timneutkens** [comment]
Let's keep this open to improve the docs, mention installing the deps basically.

**Comment by pjaws** [comment]
I'd gladly update the docs if I knew what config you were using now.

**Comment by timneutkens** [comment]
It's the same config, only thing that has to be mentioned is that the user has to install the mentioned dependencies like `postcss-flexbugs-fixes` through `npm install postcss-flexbugs-fixes` etc

**Comment by timneutkens** [comment]
Fixed by #11966

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
