### ISSUE TITLE
Error: Cannot find module 'dist/build-manifest.json'

### ISSUE THREAD

**Issue by stramel** [zeit/next.js#4598]
# Bug report

## Describe the bug

Running dev environment results in `Error: Cannot find module 'dist/build-manifest.json'`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. `yarn dev`

## Expected behavior
Application should start up

## System information
 - OS: Mac OS
 - Version of Next.js: 6.0.4-canary.4

## Additional context

Worked correctly in 6.0.4-canary.3. I assume it has to do with centralizing the distDir and re-organizing for next-server. Error seems to be originating from `node_moudles/next/dist/server/render#202` which has `buildManifest = require((0, _path.join)(distDir, _constants.BUILD_MANIFEST));`. Seems like it isn't properly resolving from the root of the project.

@timneutkens

**Comment by timneutkens** [comment]
Could you provide an example? I can't reproduce with the hello-world example.

**Comment by timneutkens** [comment]
Fixed! Thanks for the catch, I'll add a test for it soon, interestingly we didn't catch this. 

Fixed in https://github.com/zeit/next.js/commit/83b5c138100e7bb7fdf19d23b38a52d60a384427

**Comment by stramel** [comment]
_Paitently awaits for publish_ 👍

**Comment by timneutkens** [comment]
It's out

**Comment by stramel** [comment]
That fixed this issue. I did get this error but didn't seem to affect anything that I immediately noticed.

```

Error: "value" required in setHeader("Access-Control-Allow-Headers", value)
    at validateHeader (_http_outgoing.js:489:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at addCorsSupport (project/node_modules/next/dist/server/utils.js:63:7)
    at HotReloader._callee$ (project/node_modules/next/dist/server/hot-reloader.js:97:61)
    at tryCatch (project/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (project/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (project/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (project/node_modules/@babel/runtime/helpers/asyncToGenerator.js:12:30)
    at _next (project/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:9)
    at project/node_modules/@babel/runtime/helpers/asyncToGenerator.js:34:7
    at new Promise (<anonymous>)
    at new F (project/node_modules/core-js/library/modules/_export.js:36:28)
    at HotReloader.<anonymous> (project/node_modules/@babel/runtime/helpers/asyncToGenerator.js:7:12)
    at HotReloader.run (project/node_modules/next/dist/server/hot-reloader.js:192:21)
    at Server._callee14$ (project/node_modules/next/dist/server/index.js:770:41)
    at tryCatch (project/node_modules/regenerator-runtime/runtime.js:62:40)
```

**Comment by timneutkens** [comment]
I couldn't reproduce, but just to be sure: https://github.com/zeit/next.js/commit/2a1075c122c9b46ed55dad0623d96d3770ee3fee

**Comment by stramel** [comment]
It was blocking navigation after checking around a bit.  Thanks for the fix!
