### ISSUE TITLE
npm error in the learnnextjs tutorial

### ISSUE THREAD

**Issue by supersabillon** [zeit/next.js#3135]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
Should serve the pages and watch for changes

## Current Behavior
Going through the tutorial and setup its fine, I'm able to run `npm run dev` and it compiles successfully, I'm able to see "Hello Next.js" page loading, but after a few seconds the app fails.

error message:

`/Users/myname/Documents/hello-next/node_modules/next/dist/server/on-demand-entry-handler.js:323
  (0, _keys2.default)(entries).forEach(function (page) {
                               ^
TypeError: lastAccessPages.includes is not a function
    at /Users/myname/Documents/hello-next/node_modules/next/dist/server/on-demand-entry-handler.js:336:25
    at Array.forEach (native)
    at disposeInactiveEntries (/Users/myname/Documents/hello-next/node_modules/next/dist/server/on-demand-entry-handler.js:323:32)
    at null._repeat (/Users/myname/Documents/hello-next/node_modules/next/dist/server/on-demand-entry-handler.js:171:5)
    at null.wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hello-next@1.0.0 dev: next
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hello-next@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/myname/.npm/_logs/2017-10-19T23_08_17_041Z-debug.log`

## Steps to Reproduce (for bugs)
1. Finish setup in Learnnextjs
2. run `npm run dev`

## Your Environment
| Tech    | Version |
|---------|---------|
| next    |    4.1.1     |
| node    |     6.9.2    |
| OS      |    macOs 10     |
| browser |  chrome       |
| etc     |         |

**Comment by timneutkens** [comment]
Did a new release (2.4.2) can you try updating?

**Comment by darkowic** [comment]
Hello there!
Next: 4.1.4
Node: 9.0.0 (4.1.2 also)

I have the same error in tutorial - https://learnnextjs.com/basics/getting-started/first-page

It supposed to show syntax error but instead, it breaks dev server:
```
node_modules/next/dist/server/on-demand-entry-handler.js:323
  (0, _keys2.default)(entries).forEach(function (page) {
                               ^
TypeError: lastAccessPages.includes is not a function
    at /node_modules/next/dist/server/on-demand-entry-handler.js:336:25
    at Array.forEach (native)
    at disposeInactiveEntries (/node_modules/next/dist/server/on-demand-entry-handler.js:323:32)
    at null._repeat (node_modules/next/dist/server/on-demand-entry-handler.js:171:5)
    at null.wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by darkowic** [comment]
I made mistake and I didn't realize that I'm still using node 4.9 - with newest node version it works

**Comment by darkowic** [comment]
@timneutkens It would be great if there is information in documentation about required node version

**Comment by awesome-rio** [comment]
i have the same error

**Comment by quickshiftin** [comment]
FYI, like @darkowic I was also on node 4.x because I'm on a new Ubuntu 16.04 server and I installed with apt-get out of the box, which comes with node 4.x. Simply [installing node via a PPA as advised on the node website](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions) got things working.

**Comment by hanxu317317** [comment]
i update my node from 5.* to 8.5.0.  and the problem is solved

**Comment by arjunmahishi** [comment]
For me it's not working in node v10.*, its working in 8.5.0
