### ISSUE TITLE
store.runSagaTask is not a function

### ISSUE THREAD

**Issue by mtsymlov** [zeit/next.js#3878]
When working with the next-redux-saga@2.0.1, the following problem occurs when navigating through pages:

`store.runSagaTask is not a function
TypeError: store.runSagaTask is not a function
    at Function._callee$ (http://localhost:3030/_next/-/page/main.js:68018:29)
    at tryCatch (http://localhost:3030/_next/-/main.js:12074:40)
    at Generator.invoke [as _invoke] (http://localhost:3030/_next/-/main.js:12308:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:3030/_next/-/main.js:12126:21)
    at step (http://localhost:3030/_next/-/page/main.js:67952:191)
    at http://localhost:3030/_next/-/page/main.js:67952:361
    at <anonymous>`

It solves the creation of the store.runSagaTask method in the configureStore and the subsequent invocation of this method:

**Before:**
```javascript
const configureStore = () => {
  const store = createStore(
    reducer,
    composeWithDevTools(applyMiddleware(sagaMiddleware, logger)),
  );

  store.sagaTask = sagaMiddleware.run(saga);
  return store;
};
```
**After:**
```javascript
const configureStore = () => {
  const store = createStore(
    reducer,
    composeWithDevTools(applyMiddleware(sagaMiddleware, logger)),
  );

  store.runSagaTask = () => {
    store.sagaTask = sagaMiddleware.run(saga);
  };

  store.runSagaTask();
  return store;
};
```
