### ISSUE TITLE
children.join is not a function

### ISSUE THREAD

**Issue by tgoldenberg** [zeit/next.js#2175]
I'm seeing some strange behavior since upgrading to 2.4.1. 

I'm getting an error related to the `HeadManager`, and it seems similar to #910, however the behavior is different.

When the app loads for the first time, some of the Css is missing. I'm assuming this is due to the error with the `HeadManager`, since I'm loading styles through the `next/head` component.

```
<Head>
  {/* other stuff */}
  <style>{styles}</style>
</Head>
```
Here is a screenshot of the error message, along with the screen without the proper CSS. After a while, the screen refreshes with the proper CSS. This also happens in production.

<img width="1020" alt="screenshot 2017-06-05 23 53 13" src="https://cloud.githubusercontent.com/assets/10930134/26813220/ba931e16-4a4a-11e7-9903-aa0fc708f7fe.png">

![screenshot 2017-06-05 23 53 36](https://cloud.githubusercontent.com/assets/10930134/26813225/bf7a6b46-4a4a-11e7-9c25-f66528f26063.png)
![screenshot 2017-06-05 23 53 25](https://cloud.githubusercontent.com/assets/10930134/26813232/c566bdb6-4a4a-11e7-8708-59c02299662b.png)

**Comment by tgoldenberg** [comment]
Also seeing the following, which I haven't seen before updating to 2.4.1. Anyone else seeing this behavior? - 
```
[BABEL] Note: The code generator has deoptimised the styling of "/Users/user/Desktop/app/.next/dist/components/login/styles.scss" as it exceeds the max of "500KB".
```

**Comment by tgoldenberg** [comment]
Haven't figured out the `children.join` issue, but what solved the CSS issue was changing this:
```
<style>{styles}</style>
```
to this:

```
<style dangerouslySetInnerHTML={{ __html: styles }} />
```
and keeping the same .scss solution provided by @davibe - [repo](https://github.com/davibe/next.js-example-with-global-stylesheet)

Closing this, unless someone feels that the `children.join` bug is worth keeping open.

**Comment by Yuripetusko** [comment]
@tgoldenberg the problem is that using ` dangerouslySetInnerHTM` renders pages much slower at the moment. `<style jsx>` would be much better to use

**Comment by tgoldenberg** [comment]
@Yuripetusko what is the best way to use scss then? I am not a designer and would prefer to use the paradigm that I know already (scss). Scss has been around for a long time and is used in a lot of major companies. 

I just think that the framework should support this use-case. It's a little frustrating to see it swept under the rug so much, tbh. Scss has a lot of benefits over just plain CSS (use of variables, nested classes, module ordering, etc.). I mean, there is an `examples` app for just about every possible use case, so why isn't there one for scss? It confuses me. And I don't want to have to (a) re-write my entire application, or (b) learn to use a different way of using CSS that is not that widely used.

I think the framework would attract a lot of people just by adding this support. Maybe I'm missing something, though.

**Comment by timneutkens** [comment]
@tgoldenberg maybe we need to make it more obvious from the name. But this example includes scss compilation https://github.com/zeit/next.js/tree/v3-beta/examples/with-external-scoped-css

**Comment by sboudrias-aa** [comment]
Being able to render

```js
<Head>
    <style>{dropTheCSS}</style>
</Head>
```

was quite convenient to import third party plugins CSS without requiring the user to setup a full external CSS toolchain.

Also, this was working fine with `2.4.1`, not sure what happened that broke `<style>` support. To me this looks like a valid regression that should be fixed.

**Comment by tashburn** [comment]
@tgoldenberg Did you ever find a solution to your babel warning/error? I have the same issue --

```
[BABEL] Note: The code generator has deoptimised the styling of "/home/ubuntu/grok/source/.next/dist/bundles/pages/Page_Home.js" as it exceeds the max of "500KB".
```
