### ISSUE TITLE
Deployment to AWS Lambda with NextJS 6

### ISSUE THREAD

**Issue by bmg-will** [zeit/next.js#4240]
- [X] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior
The server should respond to requests without error. The below does not occur with NextJS V5 and I can deploy fine.

## Current Behavior
The server responds 'Internal Server Error' to all requests. Below is the stack trace that gets logged to CloudWatch, note the mix of forward and back slashes in the file path it is trying to resolve. I am running 'next build' (on windows) before deployment and have checked node_modules is also getting deployed.

`Error: Cannot find module '/var/task/.next/dist/bundles\pages\_error.js'
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at _callee$ (/var/task/node_modules/next/dist/server/require.js:87:46)
at tryCatch (/var/task/node_modules/regenerator-runtime/runtime.js:62:40)
at Generator.invoke [as _invoke] (/var/task/node_modules/regenerator-runtime/runtime.js:296:22)
at Generator.prototype.(anonymous function) [as next] (/var/task/node_modules/regenerator-runtime/runtime.js:114:21)
at step (/var/task/node_modules/@babel/runtime/helpers/asyncToGenerator.js:12:30)
at _next (/var/task/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:9) code: 'MODULE_NOT_FOUND'`

## Steps to Reproduce (for bugs)
1. Deploy NextJS V6 app using an express custom server to Lambda using aws-serverless-express.

## Context
Unable to upgrade to NextJS V6. 
Works fine with NextJS V5.1.0, I can deploy to Lambda and everything works seamlessly.

next.config.js
`const { PHASE_DEVELOPMENT_SERVER } = require('next/constants')

const withTypescript = require('@zeit/next-typescript');
const withSass = require('@zeit/next-sass');

module.exports = (phase, {defaultConfig}) => {
  return withTypescript(withSass({
    webpack(config, options) {
      return config;
    },
    publicRuntimeConfig: {
      API_HOST: (phase === PHASE_DEVELOPMENT_SERVER) ? 'http://localhost:4000' : 'https://api.xxxx'
    }
  }));
}`

## Your Environment
| Tech      | Version |
|----------|----------|
| next      |     6.00     |
| node     |    8.10     |
| OS         |    AWS Linux AMI (Linux kernel version – 4.9.85-38.58.amzn1.x86_64)     |

**Comment by timneutkens** [comment]
Basically we now make a mapping of pages at build time, so it's way faster to resolve them. 

Something I never expected to happen was building on one filesystem (windows) and deploying on another (linux). So I guess we have to either add an option to the webpack plugin, or replace the slashes (which I'd rather not do)

**Comment by bmg-will** [comment]
Ahh that makes sense, obvious now you have pointed it out.

I need to put my CI process in place anyway which will build it on Linux.  This issue is more down to me and my current setup than NextJs.

Thanks for response though, feel free to close this or keep open if you think it should be something you guys should be catering for.

**Comment by timneutkens** [comment]
Cool 👍 🙏

**Comment by chacbumbum** [comment]
@timneutkens How can I do in order not to build it on server?
