### ISSUE TITLE
[HMR] Hot module replacement is not working

### ISSUE THREAD

**Issue by alexandrzavalii** [zeit/next.js#12030]
# Bug report
On the most basic example on nextjs, HMR does not work.
It is stuck on `[HMR] bundle rebuilding`
After some time I get this error
```
react_devtools_backend.js:6 Error while applying updates, reloading page Error: Manifest request to /_next/static/webpack/230ce46768afbdef672e.hot-update.json timed out.
    at XMLHttpRequest.request.onreadystatechange (bootstrap:91)
```
<img width="422" alt="Screen Shot 2020-04-19 at 9 04 53 PM" src="https://user-images.githubusercontent.com/10633451/79698534-7abfbe80-8281-11ea-9b8b-cb13d2224146.png">

HMR works on older version: NextJS v7.0.0

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. npx create-next-app
2. cd your-app && yarn install
3. yarn dev
4. Try several times to make a change on index.js file and see the HMR stops working

## System information

- OS: MacOS
- Chrome
- Version of Next.js: [9.3.5]
- Version of Node.js: [13]

**Comment by timneutkens** [comment]
Tried out the steps provided but can't reproduce the issue. We also have extensive integration tests for HMR.

**Comment by alexandrzavalii** [comment]
@timneutkens  Thanks for taking a look! 
Could it be system related? Any idea what could be blocking hot-update.json requests?
Surprisingly it works with NextJS v7.0.0

**Comment by alexandrzavalii** [comment]
This helped: https://github.com/zeit/next.js/issues/9776#issuecomment-567411748
 I had service worker installed on the same port :/ 
Very annoying that console didn't have any errors related to service-worker in the console, spent a day looking for a fix.

Anyways Nextjs is awesome, thanks for building it :)

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
