### ISSUE TITLE
with-jest example not working

### ISSUE THREAD

**Issue by mckernanin** [zeit/next.js#5563]
# Examples bug report

## Example name
With Jest

## Describe the bug
Jest fails to run

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. clone the next.js repo
2. run the with-jest example

## Expected behavior
Jest should be able to run its tests.

## Additional context

Another example of the issue, Next repo with jest installed & broken:

https://github.com/mckernanin/Syntax/tree/master

**Comment by eccorley** [comment]
I took a look at this one and noticed it only seems to happen when using npm. If you clone and install deps with yarn the tests pass as expected.

If you use npm you get 'Cannot find module '@babel/core' when trying to run the tests, event though the @babel/core package is available in node_modules.

I'm still trying to figure out what the underlying difference is. I'm not too versed on exactly what yarn does differently than npm, so any help there would be appreciated.

**Comment by mckernanin** [comment]
@eccorley I get the same error using yarn. versions of things:

<img width="462" alt="screenshot 2018-10-31 15 33 15" src="https://user-images.githubusercontent.com/6300047/47820192-68b32e80-dd22-11e8-9ef3-ca7fba032de6.png">

**Comment by eccorley** [comment]
@mckernanin ah yeah looks like my yarn is still at 1.9.4

**Comment by echoulen** [comment]
try to remove `yarn.lock` and yarn again

**Comment by echoulen** [comment]
![2018-11-01 9 38 34](https://user-images.githubusercontent.com/6993621/47827626-f42bce80-ddb9-11e8-9a1b-f0e66eab86c6.png)
working fine with yarn 1.5.1

**Comment by mckernanin** [comment]
After poking at it more, I realized that I was on the canary branch. Master of the repo works just fine. There are changes to the .babelrc on master that aren't on canary. Closing issue.

**Comment by echoulen** [comment]
still working fine in canary branch
![2018-11-01 11 08 29](https://user-images.githubusercontent.com/6993621/47830382-9e115800-ddc6-11e8-9e49-c65443b09d34.png)
![2018-11-01 11 09 39](https://user-images.githubusercontent.com/6993621/47830390-a5386600-ddc6-11e8-9a4b-a7361f28be75.png)

**Comment by lucleray** [comment]
@mckernanin
Make sure you installed @babel/core, I don't see it here : https://github.com/mckernanin/Syntax/blob/master/package.json

It's necessary when you use babel-jest, see here : https://github.com/facebook/jest/tree/master/packages/babel-jest

**Comment by mckernanin** [comment]
@lucleray ok thanks! sorry, all the jest/babel deps are kinda confusing 😕

**Comment by mu7amad** [comment]
The example also doesn't work with me 
![capture](https://user-images.githubusercontent.com/7469201/48062394-2d9d7900-e1c2-11e8-8325-229281741b93.JPG)

**Comment by lucleray** [comment]
@mu7amad 
I tried : 
```
yarn create next-app --example with-jest with-jest-app
cd with-jest-app
yarn test
```

And it worked 😅
Are you sure everything was installed properly ?

**Comment by mu7amad** [comment]
@lucleray thanks for your support, I did again steps as you wrote and everything installed correctly I can run yarn dev but I can't run yarn test.
![capture](https://user-images.githubusercontent.com/7469201/48088767-1d59be00-e203-11e8-894c-ce2f2fd67660.JPG)
