### ISSUE TITLE
Default built-in postcss plugins dependency error in lastest nextjs 9.3.4

### ISSUE THREAD

**Issue by gtolarc** [zeit/next.js#11580]
After updating to 9.3.4, the following dependency error occurred. As far as I know, plugins like postcss-flexbugs-fixes are built into nextjs by default, but should I explicitly install them now?

```
> Ready on http://localhost:3000
[ ready ] compiled successfully
[ event ] build page: /
[ wait ]  compiling ...
[ error ] ./assets/global.scss
Error: Loading PostCSS Plugin failed: Cannot find module 'postcss-flexbugs-fixes'
```
