### ISSUE TITLE
[question]how to get current page full url

### ISSUE THREAD

**Issue by foxundermoon** [zeit/next.js#1553]
i'm try to get current  page full url by `window.location.href`
but it throw error on my phone. 

then  i'm change to calculate it by server request
```
   static async getInitialProps({req}) {
         let url =req.protocol + '://' + req.get('host') + req.originalUrl;
         return {url}
    }
```

but it still failure.

i'm found next Link still use window to getUrl 

```
export function getLocationOrigin () {
  const { protocol, hostname, port } = window.location
  return `${protocol}//${hostname}${port ? ':' + port : ''}`
}

export function getURL () {
  const { href } = window.location
  const origin = getLocationOrigin()
  return href.substring(origin.length)
}
```

**Comment by iaincollins** [comment]
In `getInitialProps()` you want to check if if req exists there (and if so, you are running on the server) or if not (and it is running on the client) and use the appropriate different logic for each case.

So, if you do something like this...

```javascript
  static async getInitialProps({ req, query }) {
   let fullUrl
   if (req) {
      fullUrl = req.protocol + '://' + req.get('host') + req.originalUrl
    } else {
      fullUrl = window.location.protocol+'//'+window.location.hostname+(window.location.port ? ':'+window.location.port: '');
    }
    return { fullUrl: fullUrl }
  }
```

...then accessing`this.props.fullUrl` in render you'll have the full URL.

Note: `this.props.url` is reserved (which is why I've called the property 'fullUrl' in this example).

**Comment by stevebluck** [comment]
Isn't there a `isServer` property you can use instead of `req` to check if you're on the server or not?

**Comment by arunoda** [comment]
@stevebluck there's no such property.

**Comment by arunoda** [comment]
Thanks @iaincollins for answering the question.

**Comment by stevebluck** [comment]
Ah, it comes with the next-redux-wrapper module.

**Comment by foxundermoon** [comment]
@iaincollins 

```javascript
fullUrl = req.protocol + '://' + req.get('host') + req.originalUrl
```
this code can not run well

```
req.get is not a funxtion
TypeError: req.get is not a function at Function._callee$ ..................
```

**Comment by iaincollins** [comment]
@foxundermoon It is there if you are using something Express with Next.js - and you explicitly used it in this issue when listing things you had tried, suggesting you were.

If you are are not then you can use `req.headers.host`. Use console.log() for debugging to see available options in req.

**Comment by mgburns** [comment]
Does this approach actually work on the client (Next@2.4.0)? As far as I can tell `getInitialProps` is called before the browser URL has been updated by the router. I can't see any way to access the current full URL in `getInitialProps` on both the client and server.

For context -- my use case is that I need to use the hostname / first path component to determine the location (country and language) of a request, which feeds into an API request issued in `getInitialProps()`.
